"""empty message

Revision ID: 3b3572ad38c5
Revises: 
Create Date: 2020-11-03 14:50:12.910629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b3572ad38c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('dishes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=130), nullable=False),
                    sa.Column('price', sa.Integer(), nullable=True),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('picture', sa.String(length=50), nullable=True),
                    sa.Column('category_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(('category_id',), ['categories.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('orders',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created', sa.String(length=20), nullable=True),
                    sa.Column('name', sa.String(length=30), nullable=False),
                    sa.Column('total', sa.Integer(), nullable=True),
                    sa.Column('status', sa.Integer(), nullable=True),
                    sa.Column('phone', sa.String(length=15), nullable=False),
                    sa.Column('email', sa.String(length=30), nullable=False),
                    sa.Column('delivery_address', sa.String(length=250), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(('user_id',), ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('dishes_orders',
                    sa.Column('dish_id', sa.Integer(), nullable=True),
                    sa.Column('order_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(('dish_id',), ['dishes.id'], ),
                    sa.ForeignKeyConstraint(('order_id',), ['orders.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dishes_orders')
    op.drop_table('orders')
    op.drop_table('dishes')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
